### ISSUE TITLE
Rails 5 / Rack 2 compatibility

### ISSUE THREAD

**Issue by neckhair** [biola/rack-cas#58]
Just wanted to open an issue to track changes for making the gem compatible with Rails 5 and Rack 2.

I have at least one issue right now with the ActiveRecord Session store.

I get the following error when receiving the ticket (in `store_session`):
`RuntimeError (#find_session not implemented.)`
This seems to be related to the following change to `Rack::Session::Abstract::ID`: https://github.com/rack/rack/commit/4224c028c71c4ccca7cdb3e5a10c51af797a4d4d

When using the cookie store everything seems to be working at the moment.

**Comment by adamcrown** [comment]
Thanks @neckhair. I haven't tried it on Rails 5 yet but I guess it's getting to be that time. I'll see if I can figure out the session store issue.

**Comment by adamcrown** [comment]
The `#find_session` issue was fixed in this PR https://github.com/biola/rack-cas/pull/59. I'll keep this open for a while in case any other issues come up.

**Comment by Marthyn** [comment]
I get the following error with Rails 5

```
ArgumentError at /
dump format error (user class)
```

At
```
unpack () Users/Marthyn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rack-cas-2f46d293b213/lib/rack-cas/session_store/active_record.rb
    def pack(data)
      ::Base64.encode64(Marshal.dump(data)) if data
    end
    def unpack(data)
      Marshal.load(::Base64.decode64(data)) if data
    end
  end
end
```

**Comment by adamcrown** [comment]
Sorry I haven't gotten back to you about this in a while. Are you still having this problem?

**Comment by adamcrown** [comment]
I haven't heard anything about this for a while so I'm closing it.

**Comment by ncri** [comment]
@Marthyn we keep getting lots of these errors. Any idea how to fix them? Teere is hardly anything out there on the web about this issue which appeared after we updated to rails 5.

Here is the stack trace we get:

```
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/marshal.rb:4:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/marshal.rb:4:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/cookies.rb:513:in `deserialize'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/cookies.rb:586:in `parse'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/cookies.rb:454:in `[]'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/cookie_store.rb:121:in `get_cookie'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/cookie_store.rb:96:in `block (2 levels) in unpacked_cookie_data'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:64:in `stale_session_check!'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/cookie_store.rb:95:in `block in unpacked_cookie_data'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/request.rb:57:in `fetch'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/request.rb:57:in `fetch_header'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/cookie_store.rb:94:in `unpacked_cookie_data'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/cookie_store.rb:89:in `block in extract_session_id'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:64:in `stale_session_check!'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/cookie_store.rb:88:in `extract_session_id'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/request/session.rb:52:in `block in id'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/request/session.rb:51:in `fetch'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/request/session.rb:51:in `id'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/request/session.rb:70:in `id'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:285:in `current_session_id'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:291:in `session_exists?'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/request/session.rb:184:in `exists?'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/request/session.rb:208:in `load_for_read!'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/request/session.rb:90:in `[]'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/session_serializer.rb:30:in `fetch'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/proxy.rb:212:in `user'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/proxy.rb:322:in `_perform_authentication'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/proxy.rb:104:in `authenticate'
/app/vendor/bundle/ruby/2.3.0/gems/devise-4.2.0/lib/devise/controllers/helpers.rb:124:in `current_user'
/app/vendor/bundle/ruby/2.3.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/frameworks/rails/controller.rb:19:in `user_for_paper_trail'
/app/vendor/bundle/ruby/2.3.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/frameworks/rails/controller.rb:63:in `set_paper_trail_whodunnit'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in '
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:170:in `block in halting'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:126:in `process'
/app/vendor/bundle/ruby/2.3.0/gems/actionview-5.0.0.1/lib/action_view/rendering.rb:30:in `process'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:190:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:262:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:39:in `block in serve'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `serve'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:725:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
/app/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/jquery-fileupload-rails-0.4.5/lib/jquery/fileupload/rails/middleware.rb:14:in `_call'
/app/vendor/bundle/ruby/2.3.0/gems/jquery-fileupload-rails-0.4.5/lib/jquery/fileupload/rails/middleware.rb:10:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-mobile-detect-0.4.0/lib/rack/mobile-detect.rb:164:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-attack-4.2.0/lib/rack/attack.rb:104:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:25:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
/app/vendor/bundle/ruby/2.3.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
/app/vendor/bundle/ruby/2.3.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
/app/vendor/bundle/ruby/2.3.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
/app/vendor/bundle/ruby/2.3.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/deflater.rb:35:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/ssl.rb:83:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/utf8-cleaner-0.1.1/lib/utf8-cleaner/middleware.rb:21:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `public_send'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `method_missing'
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.2.321/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/configuration.rb:225:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/server.rb:578:in `handle_request'
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/server.rb:415:in `process_client'
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/server.rb:275:in `block in run'
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```
